services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5555:5432"
    environment:
      POSTGRES_DB: docproc
      POSTGRES_USER: docproc
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  doc-proc-app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./input:/input
    container_name: doc-proc