spring:
  datasource:
    url: jdbc:postgresql://localhost:5555/docproc
    driver-class-name: org.postgresql.Driver
    username: docproc
    password: ${DB_PASSWORD}

    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000

  h2:
    console:
      enabled: false
  batch:
    jdbc:
      initialize-schema: never
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
