config:
  input-folder: ./input

spring:
  datasource:
    url: jdbc:h2:mem:kineticdb;DB_CLOSE_ON_EXIT=TRUE;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: kinetic
    password: kinetic
  h2:
    console:
      enabled: true
  batch:
    jdbc:
      initialize-schema: always
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

logging:
  level:
    root: INFO