spring:
  datasource:
    url: jdbc:h2:mem:docproc;DB_CLOSE_ON_EXIT=TRUE;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: docproc
    password: test123
  h2:
    console:
      enabled: true
  batch:
    jdbc:
      initialize-schema: always
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
